-- daily_briefings: one AI-generated morning summary per staff member per day
-- (own pm_tasks, own Google Calendar, own Gmail unread, plus firm-wide open
-- portal_requests and urgent Quo inbox items). Pre-generated by pg_cron every
-- morning (see the companion schedule migration); a staff member can also
-- trigger their own regeneration on demand. Flat staff-trust RLS, matching
-- pm_tasks/monthly_governance_reviews -- per-user filtering happens at the
-- query layer, not RLS, per this codebase's established convention.

CREATE TABLE public.daily_briefings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  briefing_date date NOT NULL,
  facts jsonb NOT NULL DEFAULT '{}'::jsonb,
  greeting text,
  summary_line text,
  priority_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  generation_status text NOT NULL DEFAULT 'generating'
    CHECK (generation_status IN ('generating', 'complete', 'error')),
  generation_error text,
  generated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (staff_user_id, briefing_date)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_briefings TO authenticated;
GRANT ALL ON public.daily_briefings TO service_role;

ALTER TABLE public.daily_briefings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff can view daily briefings"
  ON public.daily_briefings FOR SELECT TO authenticated USING (true);
CREATE POLICY "Staff can insert daily briefings"
  ON public.daily_briefings FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Staff can update daily briefings"
  ON public.daily_briefings FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Staff can delete daily briefings"
  ON public.daily_briefings FOR DELETE TO authenticated USING (true);
CREATE POLICY "Service manages daily briefings"
  ON public.daily_briefings FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE INDEX idx_daily_briefings_staff_date ON public.daily_briefings (staff_user_id, briefing_date DESC);

CREATE TRIGGER update_daily_briefings_updated_at
  BEFORE UPDATE ON public.daily_briefings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
