ALTER TABLE public.households
  ADD COLUMN IF NOT EXISTS onboarding_step INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS audit_booked_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS profile_completed_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS wealth_event_type TEXT,
  ADD COLUMN IF NOT EXISTS wealth_event_notes TEXT,
  ADD COLUMN IF NOT EXISTS wealth_event_completed_at TIMESTAMP WITH TIME ZONE;